### ISSUE TITLE
Recursive References Property set to undefined

### ISSUE THREAD

**Issue by hIASL99** [JeremyMahieu/angular-json-refs-interceptor#1]
When using this interceptor to deserialize the [Data.json](https://github.com/JeremyMahieu/angular-json-refs-interceptor/files/13559177/Data.json) in angular, the object with $id: 10 is set to undefined in the javascript object.

![serializerissue](https://github.com/JeremyMahieu/angular-json-refs-interceptor/assets/74314283/5718e572-845a-499c-a472-7eabe99e48c5)

**Comment by JeremyMahieu** [comment]
Thanks for reporting and fixing. Your fix is merged and I'll release it on npm soon.
